#!/bin/sh

set -u
set -e

if [ $# -lt 1 ]; then
	echo USAGE: $0 \<SourceForge user name\> [tag]
	exit -1
fi

TAG=
if [ $# -gt 1 ]; then
	TAG=.$2
fi

BUILDDIR=$HOME/src/vgl.nightly/latest/files
PROJWEB=/home/project-web/virtualgl/htdocs/
SSHSERVER=$1,virtualgl@shell.sourceforge.net

if [ ! -d $BUILDDIR ]; then
	echo No nightly build to upload!
	exit -1
fi

echo Uploading build ...
chmod 644 $BUILDDIR/*
ssh $SSHSERVER create
ssh $SSHSERVER mkdir $PROJWEB/vgl.nightly$TAG || true
ssh $SSHSERVER rm $PROJWEB/vgl.nightly$TAG/* || true
scp $BUILDDIR/* $SSHSERVER:$PROJWEB/vgl.nightly$TAG

exit 0
